django_project/urls.py
# django_project/urls.py
"""
URL configuration for django_project project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
    path('accounts/', include("accounts.urls")),
    path('', include("pages.urls")),
    path('middle_earth/', include("middle_earth.urls")),
    
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

pages/urls.py
# pages/urls.py
from django.urls import path
from .views import HomePageView


urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

middle_earth/models.py
from django.db import models
from django.urls import reverse
from .templatetags import custom_filters
from django.utils.html import format_html
import re

class Character(models.Model):
    class Meta:
        verbose_name_plural = "Characters"
    RACE_CHOICES = [
        ("Human", "Human"),
        ("Elf", "Elf"),
        ("Dwarf", "Dwarf"),
        ("Hobbit", "Hobbit"),
        ("Valar", "Valar"),
        ("Maiar", "Maiar"),
        ("Orc", "Orc"),
        ("Uruk-Hai", "Uruk-Hai"),
        ("Goblin", "Goblin"),
        ("Eagle", "Eagle"),
        ("Spider", "Spider"),
        ("Troll", "Troll"),
        ("Ent", "Ent"),
        ("Balrog", "Balrog"),
        ("Dragon", "Dragon"),
        ("Wight", "Wight"),
        ("Other/Unknown", "Other/Unknown"),
    ]
    name = models.CharField(max_length=100)
    aka = models.CharField(max_length=100, blank=True, null=True, verbose_name="AKA")
    race = models.CharField(max_length=100, choices=RACE_CHOICES)
    description = models.TextField(blank=True, null=True)
    picture = models.ImageField(upload_to='character_pictures/', blank=True)
    picture_credit = models.CharField(max_length=250, blank=True, null=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('verse_detail', args=[str(self.id)])
    

class Verse(models.Model):
    """Page numbers for The Lord of the Rings (The Fellowship of the Ring, The Two Towers, 
    and The Return of the King) are taken from 
    Tolkien, J. R. R. 2021. The Lord of the Rings Illustrated. William Morrow & Company.
    Also, while the printed LOTR version referenced has the entire LOTR in one volume, references 
    are given in the name of each of the individual books (The Fellowship of the Ring, containing
    Books I and II; The Two Towers, containing Books III and IV; and The Return of the King,
    containing Books V and VI). 
    
    Unless necessary to avoid confusion or (as in the case of Tom Bombadil), the speaking character 
    is almost always referred to by his/her entire name, the speaker should only be listed using 
    the first or commonly used name. For example, Frodo instead of Frodo Baggins or Sam instead of
    Sam Gamgee. Where a speaker may have more than one common name, the name the speaker uses at
    the time of speaking the verse should be used. For example, the gray wizard may be called
    Mithrandir in The Silmirillion but Gandalf in The Hobbit.

    To address difficulties in searching texts containing unicode escape codes, all words have been 
    normalized to remove any diacritical marks so common in Middle Earth literature. So, for example,
    instead of Túrin, the character's name is saved and shown as Turin.

    For all books, there are also references to "Books" and Chapters
    to facilitate use of other printed versions that may not follow the same pagination as
    the cited versions. 
    """
    class Meta:
        verbose_name_plural = "Verses"

    SILMARILLION = "SI"
    HOBBIT = "HO"
    FELLOWSHIP = "FR"
    TOWERS = "TT"
    KING = "RK"
    UNFINISHED = "UT"
    CHILDREN = "CH"
    BEREN = "BL"
    GONDOLIN = "FG"
    NUMENOR = "FN"
    BOOK_CHOICES = {
        SILMARILLION: "The Silmarillion",
        HOBBIT: "The Hobbit",
        FELLOWSHIP: "The Fellowship of the Ring",
        TOWERS: "The Two Towers",
        KING: "The Return of the King",
        UNFINISHED: "Unfinished Tales",
        CHILDREN: "The Children of Hurin",
        BEREN: "Beren and Luthien",
        GONDOLIN: "The Fall of Gondolin",
        NUMENOR: "The Fall of Numenor"
        }
    
    text = models.TextField()
    speaker = models.ManyToManyField(Character)
    context = models.TextField()
    book = models.CharField(max_length=100, choices=BOOK_CHOICES)
    sub_book = models.CharField(max_length=20, blank=True, null=True)
    chapter = models.CharField(max_length=10, blank=True, null=True)
    page = models.CharField(max_length=10, blank=True, null=True)


    def __str__(self):
        return f"{self.text[:50]}"
    
    def get_absolute_url(self):
        return reverse('character_detail', args=[str(self.id)])
    
    @property
    def blurb(self):
        # Split the text at the first line break and return the first line.
        first_line = self.text.split('\n', 1)[0]
        # filter text through tooltips to remove markup from list view
        blurb_text = custom_filters.add_tooltips(first_line)
        return format_html(blurb_text) 
    
    @property
    def plain_blurb(self):
        """Doesn't add the html that the 'blurb' property does
        and strips the annotation markup ({{...|...}})"""
        # Get the first line of the text
        first_line = self.text.split('\n', 1)[0]
        
        # Remove any {{...|...}} patterns (tooltip syntax) using regex
        plain_text = re.sub(r'\{\{(.*?)\|(.*?)\}\}', r'\1', first_line)
        
        return plain_text
    

class Place(models.Model):
    SUB_CONTINENTS_CHOICES = [
        ("Beleriand", "Beleriand"),
        ("Middle Earth at End of Third Age", "Middle Earth at End of Third Age")
    ]
    name = models.CharField(max_length=100)
    sub_continent = models.CharField(max_length=100, choices=SUB_CONTINENTS_CHOICES, blank=True, null=True)
    description = models.TextField()
    picture = models.ImageField(upload_to='place_pictures/', blank=True)
    picture_credit = models.CharField(max_length=250, blank=True, null=True)


class Thing(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    picture = models.ImageField(upload_to='thing_pictures/', blank=True)
    picture_credit = models.CharField(max_length=250, blank=True, null=True)

templates/_base.html
<!-- templates/_base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Middle Earth{% endblock title %}</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!-- Tippy.js CSS -->
    <link href="https://unpkg.com/tippy.js@6/dist/tippy.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/tippy.js@6/themes/light-border.css"
/>
    
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">The Verses of Middle Earth</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Verses</a>
                        <div class="dropdown-menu">
                            <a href="{% url 'verses_list' %}" class="dropdown-item">All Verses</a>
                            <div class="dropdown-divider"></div>
                            <h1 class="dropdown-header text-muted" style="font-size: 1.15em;">Verses By Book</h1>
                            <a href="{% url 'verses_by_book' %}?book=SI" class="dropdown-item"><em>The Silmarillion</em></a>
                            <a href="{% url 'verses_by_book' %}?book=HO" class="dropdown-item"><em>The Hobbit</em></a>
                            <a href="{% url 'verses_by_book' %}?book=FR" class="dropdown-item"><em>The Fellowship of the Ring</em></a>
                            <a href="{% url 'verses_by_book' %}?book=TT" class="dropdown-item"><em>The Two Towers</em></a>
                            <a href="{% url 'verses_by_book' %}?book=RK" class="dropdown-item"><em>The Return of the King</em></a>

                        </div>
                    </div>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'characters_list' %}">Characters</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bibliography' %}">Bibliography</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        
        {% endblock content %}
        <br>
        <div class="text-left">
            <a href="{% url 'admin:index' %}" class="invisible-link">Admin</a>
        </div>
    </div>
    <!-- Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- JavaScript -->
    <script src="{% static 'js/base.js' %}"></script>
    <!-- Tippy.js JavaScript -->
    <script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.min.js"></script>
    <script src="https://unpkg.com/tippy.js@6/dist/tippy-bundle.umd.js"></script>
</body>
</html>

templates/bibliography.html
{% extends "_base.html" %}

{% block title %}{{ block.super }}: Bibliography{% endblock title %}

{% block content %}
<h1 class="display-5 text-center">Bibliography</h1>
<br>
<p>I have tried to make it as easy as possible to locate these verses. To that end, I have tried to include book and chapter numbers for all the verses so they can be located without reference to page numbers which vary among editions. I have also provided page numbers for the editions listed below. And just a quick pedantic note: Lord of the Rings is not technically a trilogy. It is, as Douglas Anderson explains in the [GET INFO] edition, "a single novel, consisting of six books plus appendices, sometimes published in three volumes." The printed edition that I reference is, in fact, a single volume version. However, because most people read it as three separate books, I have included the well-known individual book titles when citing an individual verse's source.</p>
<br>
<h1 class="display-6">Illustrated editions from William Morrow</h1>
<p>These are my absolute favorite editions of the three main Middle Earth books. They are beautifully set, sturdy, and include fold out maps as well as many of Tolkien's own illustrations.</p>
<ul>
    <li>Tolkien, J.R.R. <cite>The Silmarillion Illustrated by J.R.R. Tolkien</cite>. William Morrow, 2022.</li>
    <li>Tolkien, J.R.R. <cite>The Hobbit Illustrated by the Author</cite>. William Morrow, 2023.</li>
    <li>Tolkien, J.R.R. <cite>The Lord of the Rings Illustrated</cite>. William Morrow, 2021.</li>
</ul>




{% endblock content %}

templates/character_detail.html
{% extends "_base.html" %}

{% block title %}{{ character.name }}{% endblock title %}

{% block content %}

<h1 class="display-5">{{ character.name }}</h1>
<p>{% if character.aka %}Also Known As: {{ character.aka }}<br>{% endif %}
    Race: {{ character.race }}<br>
</p>
<div class="row">
    <div class="col-7">
        {{ character.description|linebreaks }}<br>
        <h1 class="display-6">Verses from this character:</h1>
        <ul>
            {% for verse in verses %}
                <li><a href="{% url 'verse_detail' verse.id %}">{{ verse.blurb }}</a><br>
                    &nbsp;&nbsp;&nbsp;&nbsp;<span class="title">{{ verse.get_book_display }},</span> {% if verse.sub_book %}Book {{ verse.sub_book }}, {% endif %}Chapter {{verse.chapter }}, Page {{ verse.page }}</li>
            {% empty %}
                <li>No verses from this character</li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-1"></div>
    <div class="col">
        {% if character.picture %}
            <figure>
                <img class="img-thumbnail" src="{{ character.picture.url }}" alt="{{ character.picture_credit }}">
                <figcaption style="font-style: italic;">{{ character.picture_credit }}</figcaption>
            </figure>    
        {% endif %}
    </div>
    <div class="col-1"></div>
</div>


  <p><a href="{% url 'characters_list' %}">Back to full list of characters</a></p>

{% endblock content %} %

templates/characters_list.html
{% extends "_base.html" %}

{% block title %}{{ block.super }}: Characters{% endblock title %}

{% block content %}

<h1 class="display-6">Middle Earth Characters</h1>

{% for character in characters %}

    <a href="{% url 'character_detail' character.id %}" style="color: black;">{{ character.name }} ({{ character.race }})</a><br>

{% endfor %}

{% endblock content %}

templates/home.html
<!-- templates/home.html -->
{% extends "_base.html" %}

{% block title %}{{ block.super }}:Home{% endblock title %}

{% block content %}
    <h1 class="display-5 text-center">The Verses of Middle Earth</h1><br>
    <p class="blockquote" id="tldr"><span style="font-weight: bold; font-size: 1.25em;">TLDR: </span>This website is a passion project with a straightforward goal: to catalog all the verses from J.R.R. Tolkien's Middle-earth, including poems, songs, incantations, and other writings in verse rather than prose, and compile them in one place. Why is this a passion project? If you're curious, feel free to read on; otherwise, you can jump right in by clicking on "Verses" in the menu bar to begin exploring. One quick note: I have added (and will continue to add) annotations to some of the texts. If you see a word or phrase with a faint dotted underline, simply hover over it to read the annotation.</p>
    <hr>
    <br>
    <p><span style="font-weight: bold; font-size: 1.25em;">For those who have longer attention spans, more time, or nothing better to do: </span>When I was in 4th grade (a long, long, long time ago), Ms. Brigham would read to us every day after lunch. One of the books she read was The Hobbit. For weeks, we'd spend the half hour or so after lunch with the lights off, heads on our desks, listening to the adventures of Bilbo Baggins and a company of dwarves as they journeyed to reclaim the lost treasure hoarded in the Lonely Mountain. After that first encounter, I wasn't a superfan, but a seed had been planted. It would be nine more years (my freshman year in college) before I learned that the tale of Bilbo's big adventure was but one of many stories about this rich and beautiful and dangerous and magical and altogether fascinating world. But it wasn't until 2006 that I read The Lord of the Rings. I was blown away. Now, I wanted to read all of it. Everything. But I was also busy. Very busy. Very, very busy. Career. Young family. You know the drill.</p>

    <p>Let's face it: trying to read all of Middle Earth literature is a commitment, one that's tough to make when you're, you know, busy. However, in the last few years, things happened. My kids became adults. I, along with the rest of the world, got to spend an inordinate amount of time at home (think 2020). And I reached a point in my career where I could enjoy a little more free time. So, I took up software development and a very intentional approach to reading. The first doesn't matter much here (except for the existence of this site as a thing on the internet). The second, however ...</p>

    <p>Recently, two areas have dominated my reading: poetry and Tolkien. I was never a poetry fan--it all seemed too symbolic or abstract for me. While I easily reveled in the sublime prose of Charles Dickens or the smart and labyrinthine tales of Umberto Eco, poetry just wasn't approachable. Then, I read Coleridge's Rime of the Ancient Mariner. Something clicked, and I was hooked. My poetry library went from non-existent to being measured in shelves.</p>

    <p>But what about Tolkien? As literary world builders go, there is none better. The richness of Middle Earth's physical world and its comprehensive social, historical, and supernatural backdrop, complete with its lore and tradition(s), are enough to draw anyone into another place and time entirely. Compelling characters, stunning landscapes, stories that touch the deepest parts of the human condition—it's difficult not to love Tolkien.
    </p>

    <p>So, what do poetry and Tolkien have to do with each other? Tolkien was a poet and was at his finest when he wove verses into his Middle Earth narratives ("verses" meaning all the poems, songs, incantations, etc, that are written in verse rather than prose). These verses are not fillers or asides but integral parts of the story, often providing historical and legendary background to the narrative. They don't just say something about Middle Earth, its people, or its history. They draw us into Middle Earth as participants or, at least, as present spectators watching events unfold live. We're not just reading the words of dwarvish songs; we hear them being sung. We don't just picture the Lonely Mountain in our mind; we feel the heat of the forge, hear the sounds of hammers and anvils and, ultimately, smell the sulfur of dragon fire. Most of all, however, these verses are deeply enchanting.
    </p> 

    <blockquote>At first the beauty of the melodies and of the interwoven words in elven-tongues, even though [Frodo] understood them little, held him in a spell, as soon as he began to attend to them. Almost it seemed that the words took shape, and visions of far lands and bright things that he had never yet imagined opened out before him; and the firelit hall became like a golden mist above seas of foam that sighed upon the margins of the world. Then the enchantment became more and more dreamlike, until he felt that an endless river of swelling gold and silver was flowing over him, too multitudinous for its pattern to be comprehended; it became part of the throbbing air about him, and it drenched and drowned him. There he wandered long in a dream of music that turned into running water, and then suddenly into a voice...<br>
    <p>--<cite>The Fellowship of the Ring</cite>, Book II, Chapter 1</p></blockquote>
    
            
    <p>You should know this is by no means a comprehensive collection of all things Middle Earth. In the process of cataloging these verses, it seemed reasonable to include at least minimal information on characters, places, events, and things to round out some context -- no great details, just enough explanation to situate the words. <strong>[These sections are still being built out so please forgive any missing or unuseful information]</strong> There are, however, some excellent online resources that do provide more comprehensive and high quality reference material. In particular, I'd point you to <a href="https://tolkiengateway.net" target="blank">The Tolkien Gateway</a> and <a href="http://lotrproject.com" target="blank">LOTR Project</a> (which has amazing interactive maps and a very interesting section on LOTR statistics -- word frequency, life expectancies, etc).</p>

{% endblock content %}

templates/verse_detail.html
{% extends "_base.html" %}
{% load custom_filters %}
{% load static %}

{% block title %}{{ verse.plain_blurb }}{% endblock title %}

{% block content %}
<br>
<p style="font-size: 1.25rem;">Verse</p>
<figure>
    <blockquote class="blockquote">
        <pre><span class="verse-display">{{ verse.text|add_tooltips|safe }}</span></pre>
    </blockquote>
    <figcaption class="blockquote-footer py-2 px-2" style="font-size: .9rem;">
        Recited by {% for name in verse.speaker.all %}<a href="{% url 'character_detail' name.id %}" style="color: black;">{{ name }}</a>, {% endfor %}in <span class="title">{{ verse.get_book_display }},</span> {% if verse.sub_book %}Book {{ verse.sub_book }}, {% endif %}Chapter {{verse.chapter }}, Page {{ verse.page }}
    </figcaption>
</figure>
<hr>
<p><span style="font-size: 1.25rem;">Context</span><br>
{{ verse.context }}</p>
<footer class="footer mt-auto py-3">
      <span class="text-muted">Page numbers are taken from: <br> 
        {% if verse.book == 'FR' %}Tolkien, J. R. R. 2021. <span class="title">The Lord of the Rings Illustrated</span>. William Morrow & Company.
        {% elif verse.book == "SI" %}
        Tolkien, J.R.R. <cite>The Silmarillion Illustrated by J.R.R. Tolkien</cite>. William Morrow, 2022.
        {% endif %}</span>
  </footer>
  <br>
  <p><a href="{% url 'verses_list' %}">Back to full list of verses</a></p>

  <script src="{% static 'js/tippyjs.js' %}"></script>

{% endblock content %}

templates/verses_by_book.html
{% extends "_base.html" %}

{% block title %}{{ block.super }}: Verses{% endblock title %}

{% block content %}

<h1 class="display-6">Verses of Middle Earth</h1>

{% for verse in verses_by_book %}

    <p><a href="{% url 'verse_detail' verse.id %}" style="color: black">{{ verse.blurb }} ...</a><br>
    <span class="text-muted">&nbsp;&nbsp;&nbsp;&nbsp;&#8212; {% for name in verse.speaker.all %}{{ name }}, {% endfor %} <span class="title">{{ verse.get_book_display }},</span> {% if verse.sub_book %}Book {{ verse.sub_book }}, {% endif %}Chapter {{verse.chapter }}, Page {{ verse.page }}</span></p>

{% endfor %}

{% endblock content %}

templates/verses_home.html
{% extends "_base.html" %}

{% block title %}{{ block.super }}: Verses{% endblock title %}

{% block content %}

<h1 class="display-6">Verses of Middle Earth</h1>
<p>To see a complete list of all verses in this collection, click <a href="{% url 'verses_list' %}">Here</a></p><br>
<p>Or, you may view a list of verses by book by clicking below:</p>
<p><a href="{% url 'verses_by_book' %}?book=SI"><em>The Silmarillion</em></a></p>
<p><a href="{% url 'verses_by_book' %}?book=HO"><em>The Hobbit</em></a></p>
<p><a href="{% url 'verses_by_book' %}?book=FR"><em>The Fellowship of the Ring</em></a></p>
<p><a href="{% url 'verses_by_book' %}?book=TT"><em>The Two Towers</em></a></p>
<p><a href="{% url 'verses_by_book' %}?book=RK"><em>The Return of the King</em></a></p>


{% endblock content %}

templates/verses_list.html
{% extends "_base.html" %}
{% load custom_filters %}

{% block title %}{{ block.super }}: Verses{% endblock title %}

{% block content %}

<h1 class="display-6">Verses of Middle Earth</h1>
<p>This is a collection of all verses in <span class="title">The Lord of the Rings</span> trilogy. By "verses," I mean songs, poems, incantations, or other specific recitations Tolkien set separately from the rest of the text. Click an excerpt to be taken to the full text.</p>
{% for verse in verses %}

    <p><a href="{% url 'verse_detail' verse.id %}" style="color: black"><span>{{ verse.blurb|safe }} ...</span></a><br>
    <span class="text-muted">&nbsp;&nbsp;&nbsp;&nbsp;&#8212; {% for name in verse.speaker.all %}{{ name }}, {% endfor %} <span class="title">{{ verse.get_book_display }},</span> {% if verse.sub_book %}Book {{ verse.sub_book }}, {% endif %}Chapter {{verse.chapter }}, Page {{ verse.page }}</span></p>

{% endfor %}

{% endblock content %}

templates/verses_select_by_book.html
{% extends "_base.html" %}

{% block title %}{{ block.super }}: Verses{% endblock title %}

{% block content %}

<h1 class="display-6">Select Book</h1>

<ul>
    <li><a href="{% url 'verses_select_by_book' '?=hobbit'}">The Hobbit</a></li>
</ul>

{% endblock content %}